### ISSUE TITLE
Proposal: Docker Security using TLS

### ISSUE THREAD

**Issue by christopherobin** [Wizcorp/Dawn#7]
## Description

Currently we setup docker in HTTP mode with no security whatsoever, while this is a convenient way to test while in development, this causes some serious security issues. We should be able to expose a docker daemon to the internet without fear of the cluster becoming a botnet.

## TLS certificates

Docker providers a security mechanism through [`TLS certificates`](https://docs.docker.com/engine/security/https/), those certificates are generated by a CA that is controlled by the user and any client trying to connect must provide a valid certificate or be rejected.

Since the certificates can only be generated on a Linux server (the OpenSSL implementation on OSX cannot generate them) they could either be generated at provision time on one of the control node then downloaded on the administrator's machine, or generated inside the dawn container to be uploaded on the nodes.

## Potential concerns

While the TLS certificate mechanism seems solid enough, I feel that it should still be used with #6 until we feel confident enough with Docker's implementation to expose it to the internet.

**Comment by stelcheck** [comment]
Pretty sure that's been done. Closing.

**Comment by christopherobin** [comment]
Indeed
